"""users workouts logged_workouts

Revision ID: a156d60a74d1
Revises: c0a40abc0829
Create Date: 2019-07-26 13:09:43.017642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a156d60a74d1'
down_revision = 'c0a40abc0829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('is_strength', sa.Boolean(), nullable=True),
    sa.Column('is_cardio', sa.Boolean(), nullable=True),
    sa.Column('is_flexibility', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_type'), 'workouts', ['type'], unique=True)
    op.create_table('loggedworkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_working_out', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_working_out')
    op.drop_column('users', 'email')
    op.drop_table('loggedworkout')
    op.drop_index(op.f('ix_workouts_type'), table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###
